name: Build Container

on:
  push:
    paths: &paths
      - flake.lock
      - flake.nix
      - mkbuildcontainer.nix
      - .github/workflows/build-container.yaml
  pull_request:
    paths: *paths

env:
  # errexit and pipefail set by the runner
  SHELLOPTS: nounset

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        uses: ./.
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
